substitutions:
  _PROJECT_ID: 'iq-analitica'
  _HOSTING_TARGET: 'neps'

steps:
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'IQ_MIL'
    args: ['ci']

  - name: 'gcr.io/cloud-builders/npm'
    dir: 'IQ_MIL'
    args: ['run', 'build']

  - name: 'node:20'
    dir: 'IQ_MIL'
    entrypoint: bash
    args:
      - -c
      - |
        npm install -g firebase-tools
        firebase deploy --project=${_PROJECT_ID} --only=hosting:${_HOSTING_TARGET}

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 900s

# substitutions:
#   _PROJECT_ID: 'iq-analitica'
#   _HOSTING_TARGET: 'neps'

# steps:
#   # 1) Instalar dependencias sin ejecutar scripts (evita typecheck en postinstall)
#   - name: 'node:20'
#     dir: 'IQ_MIL'
#     entrypoint: bash
#     args:
#       - -lc
#       - |
#         npm ci --ignore-scripts --no-audit --no-fund

#   # 2) Build de producción (Vite crea ./dist)
#   - name: 'node:20'
#     dir: 'IQ_MIL'
#     entrypoint: bash
#     args:
#       - -lc
#       - |
#         npm run build

#   # 3) Deploy a Firebase Hosting usando el target "neps"
#   - name: 'node:20'
#     dir: 'IQ_MIL'
#     entrypoint: bash
#     args:
#       - -lc
#       - |
#         npm install -g firebase-tools
#         firebase deploy --project="${_PROJECT_ID}" --only="hosting:${_HOSTING_TARGET}" --non-interactive

# options:
#   logging: CLOUD_LOGGING_ONLY

# timeout: '900s'
